version: "3.2"

services:
  lnd:
    image: lnd-app
    container_name: lnd
    build:
      context: ./lnd
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-bitcoind.conf
      - ./conf/docker-lnd.conf
    command: /go/src/github.com/lightningnetwork/lnd/restart.sh
    depends_on:
      - bitcoind
      - tor
    volumes:
      - data-lnd:/root/.lnd
      - lnd-shared:/shared
      - ./lnd/restart.sh:/go/src/github.com/lightningnetwork/lnd/restart.sh
    restart: on-failure
    networks:
      dojonet:
        ipv4_address: 172.28.1.11


volumes:
  # data-lnd volume is used for persisting lnd application data and chain state
  # during container lifecycle.
  data-lnd:
  # shared volume is need to store tls certificates and access macaroons
  lnd-shared:

